---
global:
  scrape_interval: 1m
scrape_configs:
  - job_name: prometheus
    scrape_interval: 1m
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: kube-state-metrics
    static_configs:
      - targets:
          - host.docker.internal:10000
remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: <your username>
      password: <your password>

